streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/antimatter-open-publishing, user/themes/antimatter]
chromeless:
  enabled: false
display_of_git_sync_repo_link: menu
type_of_git_sync_repo_link: view
git_sync_edit_note_text: 'Have a suggestion or correction?'
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
cc_license:
  enabled: false
  type: ccby
  icon: false
displaycustommenus:
  enabled: false
hidehomemenulink: true
