title: Grav
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - category
  - tag
  - month
  - author
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: ''
