core:
  grav:
    version: 1.7.14
    history:
      version: 1.6.31
      date: '2021-01-05 20:50:15'
      0: { version: 1.7.0, date: '2021-01-20 18:04:35' }
      1: { version: 1.7.1, date: '2021-01-20 20:05:47' }
      2: { version: 1.7.5, date: '2021-02-14 19:11:35' }
      3: { version: 1.7.9, date: '2021-03-21 15:38:49' }
      4: { version: 1.7.14, date: '2021-05-11 15:21:56' }
    schema: 1.7.0_2020-11-20_1
