core:
  grav:
    version: 1.7.42.1
    history:
      version: 1.6.31
      date: '2021-01-05 20:50:15'
      0: { version: 1.7.0, date: '2021-01-20 18:04:35' }
      1: { version: 1.7.1, date: '2021-01-20 20:05:47' }
      2: { version: 1.7.5, date: '2021-02-14 19:11:35' }
      3: { version: 1.7.9, date: '2021-03-21 15:38:49' }
      4: { version: 1.7.14, date: '2021-05-11 15:21:56' }
      5: { version: 1.7.22, date: '2021-09-26 14:43:08' }
      6: { version: 1.7.25, date: '2021-11-28 18:59:55' }
      7: { version: 1.7.34, date: '2022-07-06 19:29:52' }
      8: { version: 1.7.37.1, date: '2022-10-14 20:26:18' }
      9: { version: 1.7.39.4, date: '2023-03-06 21:22:13' }
      10: { version: 1.7.40, date: '2023-03-28 18:53:46' }
      11: { version: 1.7.41.1, date: '2023-05-18 21:26:58' }
      12: { version: 1.7.42.1, date: '2023-07-05 20:36:58' }
    schema: 1.7.0_2020-11-20_1
